server {
  listen 80;
  server_name gabrielarangeladvocacia.com.br;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name gabrielarangeladvocacia.com.br;
  ssl_certificate /etc/letsencrypt/live/gabrielarangeladvocacia.com.br/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/gabrielarangeladvocacia.com.br/privkey.pem;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html =404;
  }
}